//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quantum.Tala.Service.VTCBillingService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VTCBillingService.VTCBillingServiceSoap")]
    public interface VTCBillingServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Authenticate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string Authenticate(string VTCAccountName, string VTCAccountPasswordMD5);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBalanceVcoin", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string GetBalanceVcoin(string VTCAccountName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuyItem", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string BuyItem(string VTCAccountName, string ItemCode, int ItemPrice, string UserIP, string KeyCode, string TransactionCode);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface VTCBillingServiceSoapChannel : Quantum.Tala.Service.VTCBillingService.VTCBillingServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class VTCBillingServiceSoapClient : System.ServiceModel.ClientBase<Quantum.Tala.Service.VTCBillingService.VTCBillingServiceSoap>, Quantum.Tala.Service.VTCBillingService.VTCBillingServiceSoap {
        
        public VTCBillingServiceSoapClient() {
        }
        
        public VTCBillingServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VTCBillingServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VTCBillingServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VTCBillingServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Authenticate(string VTCAccountName, string VTCAccountPasswordMD5) {
            return base.Channel.Authenticate(VTCAccountName, VTCAccountPasswordMD5);
        }
        
        public string GetBalanceVcoin(string VTCAccountName) {
            return base.Channel.GetBalanceVcoin(VTCAccountName);
        }
        
        public string BuyItem(string VTCAccountName, string ItemCode, int ItemPrice, string UserIP, string KeyCode, string TransactionCode) {
            return base.Channel.BuyItem(VTCAccountName, ItemCode, ItemPrice, UserIP, KeyCode, TransactionCode);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VTCBillingService.VTCBillingServiceHttpGet")]
    public interface VTCBillingServiceHttpGet {
        
        // CODEGEN: Generating message contract since the operation Authenticate is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VTCBillingServiceHttpGet/AuthenticateRequest", ReplyAction="http://tempuri.org/VTCBillingServiceHttpGet/AuthenticateResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Quantum.Tala.Service.VTCBillingService.AuthenticateResponse Authenticate(Quantum.Tala.Service.VTCBillingService.AuthenticateRequest request);
        
        // CODEGEN: Generating message contract since the operation GetBalanceVcoin is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VTCBillingServiceHttpGet/GetBalanceVcoinRequest", ReplyAction="http://tempuri.org/VTCBillingServiceHttpGet/GetBalanceVcoinResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Quantum.Tala.Service.VTCBillingService.GetBalanceVcoinResponse GetBalanceVcoin(Quantum.Tala.Service.VTCBillingService.GetBalanceVcoinRequest request);
        
        // CODEGEN: Generating message contract since the operation BuyItem is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VTCBillingServiceHttpGet/BuyItemRequest", ReplyAction="http://tempuri.org/VTCBillingServiceHttpGet/BuyItemResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Quantum.Tala.Service.VTCBillingService.BuyItemResponse BuyItem(Quantum.Tala.Service.VTCBillingService.BuyItemRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthenticateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string VTCAccountName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string VTCAccountPasswordMD5;
        
        public AuthenticateRequest() {
        }
        
        public AuthenticateRequest(string VTCAccountName, string VTCAccountPasswordMD5) {
            this.VTCAccountName = VTCAccountName;
            this.VTCAccountPasswordMD5 = VTCAccountPasswordMD5;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthenticateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @string;
        
        public AuthenticateResponse() {
        }
        
        public AuthenticateResponse(string @string) {
            this.@string = @string;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBalanceVcoinRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string VTCAccountName;
        
        public GetBalanceVcoinRequest() {
        }
        
        public GetBalanceVcoinRequest(string VTCAccountName) {
            this.VTCAccountName = VTCAccountName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBalanceVcoinResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @string;
        
        public GetBalanceVcoinResponse() {
        }
        
        public GetBalanceVcoinResponse(string @string) {
            this.@string = @string;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuyItemRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string VTCAccountName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string ItemCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string ItemPrice;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string UserIP;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string KeyCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string TransactionCode;
        
        public BuyItemRequest() {
        }
        
        public BuyItemRequest(string VTCAccountName, string ItemCode, string ItemPrice, string UserIP, string KeyCode, string TransactionCode) {
            this.VTCAccountName = VTCAccountName;
            this.ItemCode = ItemCode;
            this.ItemPrice = ItemPrice;
            this.UserIP = UserIP;
            this.KeyCode = KeyCode;
            this.TransactionCode = TransactionCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuyItemResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @string;
        
        public BuyItemResponse() {
        }
        
        public BuyItemResponse(string @string) {
            this.@string = @string;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface VTCBillingServiceHttpGetChannel : Quantum.Tala.Service.VTCBillingService.VTCBillingServiceHttpGet, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class VTCBillingServiceHttpGetClient : System.ServiceModel.ClientBase<Quantum.Tala.Service.VTCBillingService.VTCBillingServiceHttpGet>, Quantum.Tala.Service.VTCBillingService.VTCBillingServiceHttpGet {
        
        public VTCBillingServiceHttpGetClient() {
        }
        
        public VTCBillingServiceHttpGetClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VTCBillingServiceHttpGetClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VTCBillingServiceHttpGetClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VTCBillingServiceHttpGetClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Quantum.Tala.Service.VTCBillingService.AuthenticateResponse Quantum.Tala.Service.VTCBillingService.VTCBillingServiceHttpGet.Authenticate(Quantum.Tala.Service.VTCBillingService.AuthenticateRequest request) {
            return base.Channel.Authenticate(request);
        }
        
        public string Authenticate(string VTCAccountName, string VTCAccountPasswordMD5) {
            Quantum.Tala.Service.VTCBillingService.AuthenticateRequest inValue = new Quantum.Tala.Service.VTCBillingService.AuthenticateRequest();
            inValue.VTCAccountName = VTCAccountName;
            inValue.VTCAccountPasswordMD5 = VTCAccountPasswordMD5;
            Quantum.Tala.Service.VTCBillingService.AuthenticateResponse retVal = ((Quantum.Tala.Service.VTCBillingService.VTCBillingServiceHttpGet)(this)).Authenticate(inValue);
            return retVal.@string;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Quantum.Tala.Service.VTCBillingService.GetBalanceVcoinResponse Quantum.Tala.Service.VTCBillingService.VTCBillingServiceHttpGet.GetBalanceVcoin(Quantum.Tala.Service.VTCBillingService.GetBalanceVcoinRequest request) {
            return base.Channel.GetBalanceVcoin(request);
        }
        
        public string GetBalanceVcoin(string VTCAccountName) {
            Quantum.Tala.Service.VTCBillingService.GetBalanceVcoinRequest inValue = new Quantum.Tala.Service.VTCBillingService.GetBalanceVcoinRequest();
            inValue.VTCAccountName = VTCAccountName;
            Quantum.Tala.Service.VTCBillingService.GetBalanceVcoinResponse retVal = ((Quantum.Tala.Service.VTCBillingService.VTCBillingServiceHttpGet)(this)).GetBalanceVcoin(inValue);
            return retVal.@string;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Quantum.Tala.Service.VTCBillingService.BuyItemResponse Quantum.Tala.Service.VTCBillingService.VTCBillingServiceHttpGet.BuyItem(Quantum.Tala.Service.VTCBillingService.BuyItemRequest request) {
            return base.Channel.BuyItem(request);
        }
        
        public string BuyItem(string VTCAccountName, string ItemCode, string ItemPrice, string UserIP, string KeyCode, string TransactionCode) {
            Quantum.Tala.Service.VTCBillingService.BuyItemRequest inValue = new Quantum.Tala.Service.VTCBillingService.BuyItemRequest();
            inValue.VTCAccountName = VTCAccountName;
            inValue.ItemCode = ItemCode;
            inValue.ItemPrice = ItemPrice;
            inValue.UserIP = UserIP;
            inValue.KeyCode = KeyCode;
            inValue.TransactionCode = TransactionCode;
            Quantum.Tala.Service.VTCBillingService.BuyItemResponse retVal = ((Quantum.Tala.Service.VTCBillingService.VTCBillingServiceHttpGet)(this)).BuyItem(inValue);
            return retVal.@string;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VTCBillingService.VTCBillingServiceHttpPost")]
    public interface VTCBillingServiceHttpPost {
        
        // CODEGEN: Generating message contract since the operation Authenticate is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VTCBillingServiceHttpPost/AuthenticateRequest", ReplyAction="http://tempuri.org/VTCBillingServiceHttpPost/AuthenticateResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Quantum.Tala.Service.VTCBillingService.AuthenticateResponse1 Authenticate(Quantum.Tala.Service.VTCBillingService.AuthenticateRequest1 request);
        
        // CODEGEN: Generating message contract since the operation GetBalanceVcoin is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VTCBillingServiceHttpPost/GetBalanceVcoinRequest", ReplyAction="http://tempuri.org/VTCBillingServiceHttpPost/GetBalanceVcoinResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Quantum.Tala.Service.VTCBillingService.GetBalanceVcoinResponse1 GetBalanceVcoin(Quantum.Tala.Service.VTCBillingService.GetBalanceVcoinRequest1 request);
        
        // CODEGEN: Generating message contract since the operation BuyItem is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VTCBillingServiceHttpPost/BuyItemRequest", ReplyAction="http://tempuri.org/VTCBillingServiceHttpPost/BuyItemResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Quantum.Tala.Service.VTCBillingService.BuyItemResponse1 BuyItem(Quantum.Tala.Service.VTCBillingService.BuyItemRequest1 request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthenticateRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string VTCAccountName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string VTCAccountPasswordMD5;
        
        public AuthenticateRequest1() {
        }
        
        public AuthenticateRequest1(string VTCAccountName, string VTCAccountPasswordMD5) {
            this.VTCAccountName = VTCAccountName;
            this.VTCAccountPasswordMD5 = VTCAccountPasswordMD5;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthenticateResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @string;
        
        public AuthenticateResponse1() {
        }
        
        public AuthenticateResponse1(string @string) {
            this.@string = @string;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBalanceVcoinRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string VTCAccountName;
        
        public GetBalanceVcoinRequest1() {
        }
        
        public GetBalanceVcoinRequest1(string VTCAccountName) {
            this.VTCAccountName = VTCAccountName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBalanceVcoinResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @string;
        
        public GetBalanceVcoinResponse1() {
        }
        
        public GetBalanceVcoinResponse1(string @string) {
            this.@string = @string;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuyItemRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string VTCAccountName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string ItemCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string ItemPrice;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string UserIP;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string KeyCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string TransactionCode;
        
        public BuyItemRequest1() {
        }
        
        public BuyItemRequest1(string VTCAccountName, string ItemCode, string ItemPrice, string UserIP, string KeyCode, string TransactionCode) {
            this.VTCAccountName = VTCAccountName;
            this.ItemCode = ItemCode;
            this.ItemPrice = ItemPrice;
            this.UserIP = UserIP;
            this.KeyCode = KeyCode;
            this.TransactionCode = TransactionCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuyItemResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @string;
        
        public BuyItemResponse1() {
        }
        
        public BuyItemResponse1(string @string) {
            this.@string = @string;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface VTCBillingServiceHttpPostChannel : Quantum.Tala.Service.VTCBillingService.VTCBillingServiceHttpPost, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class VTCBillingServiceHttpPostClient : System.ServiceModel.ClientBase<Quantum.Tala.Service.VTCBillingService.VTCBillingServiceHttpPost>, Quantum.Tala.Service.VTCBillingService.VTCBillingServiceHttpPost {
        
        public VTCBillingServiceHttpPostClient() {
        }
        
        public VTCBillingServiceHttpPostClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VTCBillingServiceHttpPostClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VTCBillingServiceHttpPostClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VTCBillingServiceHttpPostClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Quantum.Tala.Service.VTCBillingService.AuthenticateResponse1 Quantum.Tala.Service.VTCBillingService.VTCBillingServiceHttpPost.Authenticate(Quantum.Tala.Service.VTCBillingService.AuthenticateRequest1 request) {
            return base.Channel.Authenticate(request);
        }
        
        public string Authenticate(string VTCAccountName, string VTCAccountPasswordMD5) {
            Quantum.Tala.Service.VTCBillingService.AuthenticateRequest1 inValue = new Quantum.Tala.Service.VTCBillingService.AuthenticateRequest1();
            inValue.VTCAccountName = VTCAccountName;
            inValue.VTCAccountPasswordMD5 = VTCAccountPasswordMD5;
            Quantum.Tala.Service.VTCBillingService.AuthenticateResponse1 retVal = ((Quantum.Tala.Service.VTCBillingService.VTCBillingServiceHttpPost)(this)).Authenticate(inValue);
            return retVal.@string;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Quantum.Tala.Service.VTCBillingService.GetBalanceVcoinResponse1 Quantum.Tala.Service.VTCBillingService.VTCBillingServiceHttpPost.GetBalanceVcoin(Quantum.Tala.Service.VTCBillingService.GetBalanceVcoinRequest1 request) {
            return base.Channel.GetBalanceVcoin(request);
        }
        
        public string GetBalanceVcoin(string VTCAccountName) {
            Quantum.Tala.Service.VTCBillingService.GetBalanceVcoinRequest1 inValue = new Quantum.Tala.Service.VTCBillingService.GetBalanceVcoinRequest1();
            inValue.VTCAccountName = VTCAccountName;
            Quantum.Tala.Service.VTCBillingService.GetBalanceVcoinResponse1 retVal = ((Quantum.Tala.Service.VTCBillingService.VTCBillingServiceHttpPost)(this)).GetBalanceVcoin(inValue);
            return retVal.@string;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Quantum.Tala.Service.VTCBillingService.BuyItemResponse1 Quantum.Tala.Service.VTCBillingService.VTCBillingServiceHttpPost.BuyItem(Quantum.Tala.Service.VTCBillingService.BuyItemRequest1 request) {
            return base.Channel.BuyItem(request);
        }
        
        public string BuyItem(string VTCAccountName, string ItemCode, string ItemPrice, string UserIP, string KeyCode, string TransactionCode) {
            Quantum.Tala.Service.VTCBillingService.BuyItemRequest1 inValue = new Quantum.Tala.Service.VTCBillingService.BuyItemRequest1();
            inValue.VTCAccountName = VTCAccountName;
            inValue.ItemCode = ItemCode;
            inValue.ItemPrice = ItemPrice;
            inValue.UserIP = UserIP;
            inValue.KeyCode = KeyCode;
            inValue.TransactionCode = TransactionCode;
            Quantum.Tala.Service.VTCBillingService.BuyItemResponse1 retVal = ((Quantum.Tala.Service.VTCBillingService.VTCBillingServiceHttpPost)(this)).BuyItem(inValue);
            return retVal.@string;
        }
    }
}
