//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quantum.Tala.Service.VTCBillingService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthenResponse", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class AuthenResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DecriptionField;
        
        private int AccountIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SignField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ResponseCode {
            get {
                return this.ResponseCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseCodeField, value) != true)) {
                    this.ResponseCodeField = value;
                    this.RaisePropertyChanged("ResponseCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Decription {
            get {
                return this.DecriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DecriptionField, value) != true)) {
                    this.DecriptionField = value;
                    this.RaisePropertyChanged("Decription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int AccountID {
            get {
                return this.AccountIDField;
            }
            set {
                if ((this.AccountIDField.Equals(value) != true)) {
                    this.AccountIDField = value;
                    this.RaisePropertyChanged("AccountID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Sign {
            get {
                return this.SignField;
            }
            set {
                if ((object.ReferenceEquals(this.SignField, value) != true)) {
                    this.SignField = value;
                    this.RaisePropertyChanged("Sign");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BalanceResponse", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class BalanceResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseCodeField;
        
        private int BalanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DecriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SignField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ResponseCode {
            get {
                return this.ResponseCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseCodeField, value) != true)) {
                    this.ResponseCodeField = value;
                    this.RaisePropertyChanged("ResponseCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int Balance {
            get {
                return this.BalanceField;
            }
            set {
                if ((this.BalanceField.Equals(value) != true)) {
                    this.BalanceField = value;
                    this.RaisePropertyChanged("Balance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Decription {
            get {
                return this.DecriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DecriptionField, value) != true)) {
                    this.DecriptionField = value;
                    this.RaisePropertyChanged("Decription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Sign {
            get {
                return this.SignField;
            }
            set {
                if ((object.ReferenceEquals(this.SignField, value) != true)) {
                    this.SignField = value;
                    this.RaisePropertyChanged("Sign");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BuyItemsResponse", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class BuyItemsResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseCodeField;
        
        private int BalanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DecriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SignField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ResponseCode {
            get {
                return this.ResponseCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseCodeField, value) != true)) {
                    this.ResponseCodeField = value;
                    this.RaisePropertyChanged("ResponseCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int Balance {
            get {
                return this.BalanceField;
            }
            set {
                if ((this.BalanceField.Equals(value) != true)) {
                    this.BalanceField = value;
                    this.RaisePropertyChanged("Balance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Decription {
            get {
                return this.DecriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DecriptionField, value) != true)) {
                    this.DecriptionField = value;
                    this.RaisePropertyChanged("Decription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Sign {
            get {
                return this.SignField;
            }
            set {
                if ((object.ReferenceEquals(this.SignField, value) != true)) {
                    this.SignField = value;
                    this.RaisePropertyChanged("Sign");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VTCBillingService.VTCBillingServiceSoap")]
    public interface VTCBillingServiceSoap {
        
        // CODEGEN: Generating message contract since element name VTCAccountName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Authenticate", ReplyAction="*")]
        Quantum.Tala.Service.VTCBillingService.AuthenticateResponse Authenticate(Quantum.Tala.Service.VTCBillingService.AuthenticateRequest request);
        
        // CODEGEN: Generating message contract since element name VTCAccountName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBalance", ReplyAction="*")]
        Quantum.Tala.Service.VTCBillingService.GetBalanceResponse GetBalance(Quantum.Tala.Service.VTCBillingService.GetBalanceRequest request);
        
        // CODEGEN: Generating message contract since element name VTCAccountName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuyItem", ReplyAction="*")]
        Quantum.Tala.Service.VTCBillingService.BuyItemResponse BuyItem(Quantum.Tala.Service.VTCBillingService.BuyItemRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthenticateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Authenticate", Namespace="http://tempuri.org/", Order=0)]
        public Quantum.Tala.Service.VTCBillingService.AuthenticateRequestBody Body;
        
        public AuthenticateRequest() {
        }
        
        public AuthenticateRequest(Quantum.Tala.Service.VTCBillingService.AuthenticateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthenticateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string VTCAccountName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string VTCAccountPasswordMD5;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string MakerCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Sign;
        
        public AuthenticateRequestBody() {
        }
        
        public AuthenticateRequestBody(string VTCAccountName, string VTCAccountPasswordMD5, string MakerCode, string Sign) {
            this.VTCAccountName = VTCAccountName;
            this.VTCAccountPasswordMD5 = VTCAccountPasswordMD5;
            this.MakerCode = MakerCode;
            this.Sign = Sign;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthenticateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AuthenticateResponse", Namespace="http://tempuri.org/", Order=0)]
        public Quantum.Tala.Service.VTCBillingService.AuthenticateResponseBody Body;
        
        public AuthenticateResponse() {
        }
        
        public AuthenticateResponse(Quantum.Tala.Service.VTCBillingService.AuthenticateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthenticateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Quantum.Tala.Service.VTCBillingService.AuthenResponse AuthenticateResult;
        
        public AuthenticateResponseBody() {
        }
        
        public AuthenticateResponseBody(Quantum.Tala.Service.VTCBillingService.AuthenResponse AuthenticateResult) {
            this.AuthenticateResult = AuthenticateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBalanceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBalance", Namespace="http://tempuri.org/", Order=0)]
        public Quantum.Tala.Service.VTCBillingService.GetBalanceRequestBody Body;
        
        public GetBalanceRequest() {
        }
        
        public GetBalanceRequest(Quantum.Tala.Service.VTCBillingService.GetBalanceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBalanceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string VTCAccountName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string MakerCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Sign;
        
        public GetBalanceRequestBody() {
        }
        
        public GetBalanceRequestBody(string VTCAccountName, string MakerCode, string Sign) {
            this.VTCAccountName = VTCAccountName;
            this.MakerCode = MakerCode;
            this.Sign = Sign;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBalanceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBalanceResponse", Namespace="http://tempuri.org/", Order=0)]
        public Quantum.Tala.Service.VTCBillingService.GetBalanceResponseBody Body;
        
        public GetBalanceResponse() {
        }
        
        public GetBalanceResponse(Quantum.Tala.Service.VTCBillingService.GetBalanceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBalanceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Quantum.Tala.Service.VTCBillingService.BalanceResponse GetBalanceResult;
        
        public GetBalanceResponseBody() {
        }
        
        public GetBalanceResponseBody(Quantum.Tala.Service.VTCBillingService.BalanceResponse GetBalanceResult) {
            this.GetBalanceResult = GetBalanceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuyItemRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuyItem", Namespace="http://tempuri.org/", Order=0)]
        public Quantum.Tala.Service.VTCBillingService.BuyItemRequestBody Body;
        
        public BuyItemRequest() {
        }
        
        public BuyItemRequest(Quantum.Tala.Service.VTCBillingService.BuyItemRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BuyItemRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string VTCAccountName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int VTCAccountID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string MakerCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ItemCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int ItemPrice;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string UserIP;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string TransactionCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Sign;
        
        public BuyItemRequestBody() {
        }
        
        public BuyItemRequestBody(string VTCAccountName, int VTCAccountID, string MakerCode, string ItemCode, int ItemPrice, string UserIP, string TransactionCode, string Sign) {
            this.VTCAccountName = VTCAccountName;
            this.VTCAccountID = VTCAccountID;
            this.MakerCode = MakerCode;
            this.ItemCode = ItemCode;
            this.ItemPrice = ItemPrice;
            this.UserIP = UserIP;
            this.TransactionCode = TransactionCode;
            this.Sign = Sign;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuyItemResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuyItemResponse", Namespace="http://tempuri.org/", Order=0)]
        public Quantum.Tala.Service.VTCBillingService.BuyItemResponseBody Body;
        
        public BuyItemResponse() {
        }
        
        public BuyItemResponse(Quantum.Tala.Service.VTCBillingService.BuyItemResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BuyItemResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Quantum.Tala.Service.VTCBillingService.BuyItemsResponse BuyItemResult;
        
        public BuyItemResponseBody() {
        }
        
        public BuyItemResponseBody(Quantum.Tala.Service.VTCBillingService.BuyItemsResponse BuyItemResult) {
            this.BuyItemResult = BuyItemResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface VTCBillingServiceSoapChannel : Quantum.Tala.Service.VTCBillingService.VTCBillingServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class VTCBillingServiceSoapClient : System.ServiceModel.ClientBase<Quantum.Tala.Service.VTCBillingService.VTCBillingServiceSoap>, Quantum.Tala.Service.VTCBillingService.VTCBillingServiceSoap {
        
        public VTCBillingServiceSoapClient() {
        }
        
        public VTCBillingServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VTCBillingServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VTCBillingServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VTCBillingServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Quantum.Tala.Service.VTCBillingService.AuthenticateResponse Quantum.Tala.Service.VTCBillingService.VTCBillingServiceSoap.Authenticate(Quantum.Tala.Service.VTCBillingService.AuthenticateRequest request) {
            return base.Channel.Authenticate(request);
        }
        
        public Quantum.Tala.Service.VTCBillingService.AuthenResponse Authenticate(string VTCAccountName, string VTCAccountPasswordMD5, string MakerCode, string Sign) {
            Quantum.Tala.Service.VTCBillingService.AuthenticateRequest inValue = new Quantum.Tala.Service.VTCBillingService.AuthenticateRequest();
            inValue.Body = new Quantum.Tala.Service.VTCBillingService.AuthenticateRequestBody();
            inValue.Body.VTCAccountName = VTCAccountName;
            inValue.Body.VTCAccountPasswordMD5 = VTCAccountPasswordMD5;
            inValue.Body.MakerCode = MakerCode;
            inValue.Body.Sign = Sign;
            Quantum.Tala.Service.VTCBillingService.AuthenticateResponse retVal = ((Quantum.Tala.Service.VTCBillingService.VTCBillingServiceSoap)(this)).Authenticate(inValue);
            return retVal.Body.AuthenticateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Quantum.Tala.Service.VTCBillingService.GetBalanceResponse Quantum.Tala.Service.VTCBillingService.VTCBillingServiceSoap.GetBalance(Quantum.Tala.Service.VTCBillingService.GetBalanceRequest request) {
            return base.Channel.GetBalance(request);
        }
        
        public Quantum.Tala.Service.VTCBillingService.BalanceResponse GetBalance(string VTCAccountName, string MakerCode, string Sign) {
            Quantum.Tala.Service.VTCBillingService.GetBalanceRequest inValue = new Quantum.Tala.Service.VTCBillingService.GetBalanceRequest();
            inValue.Body = new Quantum.Tala.Service.VTCBillingService.GetBalanceRequestBody();
            inValue.Body.VTCAccountName = VTCAccountName;
            inValue.Body.MakerCode = MakerCode;
            inValue.Body.Sign = Sign;
            Quantum.Tala.Service.VTCBillingService.GetBalanceResponse retVal = ((Quantum.Tala.Service.VTCBillingService.VTCBillingServiceSoap)(this)).GetBalance(inValue);
            return retVal.Body.GetBalanceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Quantum.Tala.Service.VTCBillingService.BuyItemResponse Quantum.Tala.Service.VTCBillingService.VTCBillingServiceSoap.BuyItem(Quantum.Tala.Service.VTCBillingService.BuyItemRequest request) {
            return base.Channel.BuyItem(request);
        }
        
        public Quantum.Tala.Service.VTCBillingService.BuyItemsResponse BuyItem(string VTCAccountName, int VTCAccountID, string MakerCode, string ItemCode, int ItemPrice, string UserIP, string TransactionCode, string Sign) {
            Quantum.Tala.Service.VTCBillingService.BuyItemRequest inValue = new Quantum.Tala.Service.VTCBillingService.BuyItemRequest();
            inValue.Body = new Quantum.Tala.Service.VTCBillingService.BuyItemRequestBody();
            inValue.Body.VTCAccountName = VTCAccountName;
            inValue.Body.VTCAccountID = VTCAccountID;
            inValue.Body.MakerCode = MakerCode;
            inValue.Body.ItemCode = ItemCode;
            inValue.Body.ItemPrice = ItemPrice;
            inValue.Body.UserIP = UserIP;
            inValue.Body.TransactionCode = TransactionCode;
            inValue.Body.Sign = Sign;
            Quantum.Tala.Service.VTCBillingService.BuyItemResponse retVal = ((Quantum.Tala.Service.VTCBillingService.VTCBillingServiceSoap)(this)).BuyItem(inValue);
            return retVal.Body.BuyItemResult;
        }
    }
}
