//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestBusiness.WSVTCGateTopup {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VTCGateTransStateInfo", Namespace="http://paygate.vtc.vn/VTCGateTopup")]
    [System.SerializableAttribute()]
    public partial class VTCGateTransStateInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long OrgTransIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataSignField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long OrgTransId {
            get {
                return this.OrgTransIdField;
            }
            set {
                if ((this.OrgTransIdField.Equals(value) != true)) {
                    this.OrgTransIdField = value;
                    this.RaisePropertyChanged("OrgTransId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ResponseCode {
            get {
                return this.ResponseCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseCodeField, value) != true)) {
                    this.ResponseCodeField = value;
                    this.RaisePropertyChanged("ResponseCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string DataSign {
            get {
                return this.DataSignField;
            }
            set {
                if ((object.ReferenceEquals(this.DataSignField, value) != true)) {
                    this.DataSignField = value;
                    this.RaisePropertyChanged("DataSign");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VTCGateResponse", Namespace="http://paygate.vtc.vn/VTCGateTopup")]
    [System.SerializableAttribute()]
    public partial class VTCGateResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountField;
        
        private double AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MakerCodeField;
        
        private System.DateTime TransDateField;
        
        private long OrgTransIdField;
        
        private long BalanceField;
        
        private long VTCTransCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataSignField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ServiceCode {
            get {
                return this.ServiceCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceCodeField, value) != true)) {
                    this.ServiceCodeField = value;
                    this.RaisePropertyChanged("ServiceCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Account {
            get {
                return this.AccountField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountField, value) != true)) {
                    this.AccountField = value;
                    this.RaisePropertyChanged("Account");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public double Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string MakerCode {
            get {
                return this.MakerCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.MakerCodeField, value) != true)) {
                    this.MakerCodeField = value;
                    this.RaisePropertyChanged("MakerCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime TransDate {
            get {
                return this.TransDateField;
            }
            set {
                if ((this.TransDateField.Equals(value) != true)) {
                    this.TransDateField = value;
                    this.RaisePropertyChanged("TransDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public long OrgTransId {
            get {
                return this.OrgTransIdField;
            }
            set {
                if ((this.OrgTransIdField.Equals(value) != true)) {
                    this.OrgTransIdField = value;
                    this.RaisePropertyChanged("OrgTransId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public long Balance {
            get {
                return this.BalanceField;
            }
            set {
                if ((this.BalanceField.Equals(value) != true)) {
                    this.BalanceField = value;
                    this.RaisePropertyChanged("Balance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public long VTCTransCode {
            get {
                return this.VTCTransCodeField;
            }
            set {
                if ((this.VTCTransCodeField.Equals(value) != true)) {
                    this.VTCTransCodeField = value;
                    this.RaisePropertyChanged("VTCTransCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string ResponseCode {
            get {
                return this.ResponseCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseCodeField, value) != true)) {
                    this.ResponseCodeField = value;
                    this.RaisePropertyChanged("ResponseCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string DataSign {
            get {
                return this.DataSignField;
            }
            set {
                if ((object.ReferenceEquals(this.DataSignField, value) != true)) {
                    this.DataSignField = value;
                    this.RaisePropertyChanged("DataSign");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountInfo", Namespace="http://paygate.vtc.vn/VTCGateTopup")]
    [System.SerializableAttribute()]
    public partial class AccountInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int errorCodeField;
        
        private int balanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string accounttopupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string datasignField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                if ((this.errorCodeField.Equals(value) != true)) {
                    this.errorCodeField = value;
                    this.RaisePropertyChanged("errorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int balance {
            get {
                return this.balanceField;
            }
            set {
                if ((this.balanceField.Equals(value) != true)) {
                    this.balanceField = value;
                    this.RaisePropertyChanged("balance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string accounttopup {
            get {
                return this.accounttopupField;
            }
            set {
                if ((object.ReferenceEquals(this.accounttopupField, value) != true)) {
                    this.accounttopupField = value;
                    this.RaisePropertyChanged("accounttopup");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string datasign {
            get {
                return this.datasignField;
            }
            set {
                if ((object.ReferenceEquals(this.datasignField, value) != true)) {
                    this.datasignField = value;
                    this.RaisePropertyChanged("datasign");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://paygate.vtc.vn/VTCGateTopup", ConfigurationName="WSVTCGateTopup.VTCGateTopupSoap")]
    public interface VTCGateTopupSoap {
        
        // CODEGEN: Generating message contract since element name MakerCode from namespace http://paygate.vtc.vn/VTCGateTopup is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://paygate.vtc.vn/VTCGateTopup/CheckStatusTransaction", ReplyAction="*")]
        TestBusiness.WSVTCGateTopup.CheckStatusTransactionResponse CheckStatusTransaction(TestBusiness.WSVTCGateTopup.CheckStatusTransactionRequest request);
        
        // CODEGEN: Generating message contract since element name ServiceCode from namespace http://paygate.vtc.vn/VTCGateTopup is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://paygate.vtc.vn/VTCGateTopup/TopupAccount", ReplyAction="*")]
        TestBusiness.WSVTCGateTopup.TopupAccountResponse TopupAccount(TestBusiness.WSVTCGateTopup.TopupAccountRequest request);
        
        // CODEGEN: Generating message contract since element name ServiceCode from namespace http://paygate.vtc.vn/VTCGateTopup is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://paygate.vtc.vn/VTCGateTopup/CheckAccountEXISTS", ReplyAction="*")]
        TestBusiness.WSVTCGateTopup.CheckAccountEXISTSResponse CheckAccountEXISTS(TestBusiness.WSVTCGateTopup.CheckAccountEXISTSRequest request);
        
        // CODEGEN: Generating message contract since element name MakerCode from namespace http://paygate.vtc.vn/VTCGateTopup is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://paygate.vtc.vn/VTCGateTopup/GetBalance", ReplyAction="*")]
        TestBusiness.WSVTCGateTopup.GetBalanceResponse GetBalance(TestBusiness.WSVTCGateTopup.GetBalanceRequest request);
        
        // CODEGEN: Generating message contract since element name MakerCode from namespace http://paygate.vtc.vn/VTCGateTopup is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://paygate.vtc.vn/VTCGateTopup/GetAccountInfo", ReplyAction="*")]
        TestBusiness.WSVTCGateTopup.GetAccountInfoResponse GetAccountInfo(TestBusiness.WSVTCGateTopup.GetAccountInfoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckStatusTransactionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckStatusTransaction", Namespace="http://paygate.vtc.vn/VTCGateTopup", Order=0)]
        public TestBusiness.WSVTCGateTopup.CheckStatusTransactionRequestBody Body;
        
        public CheckStatusTransactionRequest() {
        }
        
        public CheckStatusTransactionRequest(TestBusiness.WSVTCGateTopup.CheckStatusTransactionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://paygate.vtc.vn/VTCGateTopup")]
    public partial class CheckStatusTransactionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string MakerCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ServiceCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public long OrgTransId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string DataSign;
        
        public CheckStatusTransactionRequestBody() {
        }
        
        public CheckStatusTransactionRequestBody(string MakerCode, string ServiceCode, long OrgTransId, string DataSign) {
            this.MakerCode = MakerCode;
            this.ServiceCode = ServiceCode;
            this.OrgTransId = OrgTransId;
            this.DataSign = DataSign;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckStatusTransactionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckStatusTransactionResponse", Namespace="http://paygate.vtc.vn/VTCGateTopup", Order=0)]
        public TestBusiness.WSVTCGateTopup.CheckStatusTransactionResponseBody Body;
        
        public CheckStatusTransactionResponse() {
        }
        
        public CheckStatusTransactionResponse(TestBusiness.WSVTCGateTopup.CheckStatusTransactionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://paygate.vtc.vn/VTCGateTopup")]
    public partial class CheckStatusTransactionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TestBusiness.WSVTCGateTopup.VTCGateTransStateInfo CheckStatusTransactionResult;
        
        public CheckStatusTransactionResponseBody() {
        }
        
        public CheckStatusTransactionResponseBody(TestBusiness.WSVTCGateTopup.VTCGateTransStateInfo CheckStatusTransactionResult) {
            this.CheckStatusTransactionResult = CheckStatusTransactionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TopupAccountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TopupAccount", Namespace="http://paygate.vtc.vn/VTCGateTopup", Order=0)]
        public TestBusiness.WSVTCGateTopup.TopupAccountRequestBody Body;
        
        public TopupAccountRequest() {
        }
        
        public TopupAccountRequest(TestBusiness.WSVTCGateTopup.TopupAccountRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://paygate.vtc.vn/VTCGateTopup")]
    public partial class TopupAccountRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ServiceCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Account;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public double Amount;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string MakerCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.DateTime TransDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public long OrgTransId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string DataSign;
        
        public TopupAccountRequestBody() {
        }
        
        public TopupAccountRequestBody(string ServiceCode, string Account, double Amount, string MakerCode, System.DateTime TransDate, long OrgTransId, string DataSign) {
            this.ServiceCode = ServiceCode;
            this.Account = Account;
            this.Amount = Amount;
            this.MakerCode = MakerCode;
            this.TransDate = TransDate;
            this.OrgTransId = OrgTransId;
            this.DataSign = DataSign;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TopupAccountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TopupAccountResponse", Namespace="http://paygate.vtc.vn/VTCGateTopup", Order=0)]
        public TestBusiness.WSVTCGateTopup.TopupAccountResponseBody Body;
        
        public TopupAccountResponse() {
        }
        
        public TopupAccountResponse(TestBusiness.WSVTCGateTopup.TopupAccountResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://paygate.vtc.vn/VTCGateTopup")]
    public partial class TopupAccountResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TestBusiness.WSVTCGateTopup.VTCGateResponse TopupAccountResult;
        
        public TopupAccountResponseBody() {
        }
        
        public TopupAccountResponseBody(TestBusiness.WSVTCGateTopup.VTCGateResponse TopupAccountResult) {
            this.TopupAccountResult = TopupAccountResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckAccountEXISTSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckAccountEXISTS", Namespace="http://paygate.vtc.vn/VTCGateTopup", Order=0)]
        public TestBusiness.WSVTCGateTopup.CheckAccountEXISTSRequestBody Body;
        
        public CheckAccountEXISTSRequest() {
        }
        
        public CheckAccountEXISTSRequest(TestBusiness.WSVTCGateTopup.CheckAccountEXISTSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://paygate.vtc.vn/VTCGateTopup")]
    public partial class CheckAccountEXISTSRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ServiceCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Account;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string MakerCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string DataSign;
        
        public CheckAccountEXISTSRequestBody() {
        }
        
        public CheckAccountEXISTSRequestBody(string ServiceCode, string Account, string MakerCode, string DataSign) {
            this.ServiceCode = ServiceCode;
            this.Account = Account;
            this.MakerCode = MakerCode;
            this.DataSign = DataSign;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckAccountEXISTSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckAccountEXISTSResponse", Namespace="http://paygate.vtc.vn/VTCGateTopup", Order=0)]
        public TestBusiness.WSVTCGateTopup.CheckAccountEXISTSResponseBody Body;
        
        public CheckAccountEXISTSResponse() {
        }
        
        public CheckAccountEXISTSResponse(TestBusiness.WSVTCGateTopup.CheckAccountEXISTSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://paygate.vtc.vn/VTCGateTopup")]
    public partial class CheckAccountEXISTSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CheckAccountEXISTSResult;
        
        public CheckAccountEXISTSResponseBody() {
        }
        
        public CheckAccountEXISTSResponseBody(string CheckAccountEXISTSResult) {
            this.CheckAccountEXISTSResult = CheckAccountEXISTSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBalanceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBalance", Namespace="http://paygate.vtc.vn/VTCGateTopup", Order=0)]
        public TestBusiness.WSVTCGateTopup.GetBalanceRequestBody Body;
        
        public GetBalanceRequest() {
        }
        
        public GetBalanceRequest(TestBusiness.WSVTCGateTopup.GetBalanceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://paygate.vtc.vn/VTCGateTopup")]
    public partial class GetBalanceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string MakerCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ServiceCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string DataSign;
        
        public GetBalanceRequestBody() {
        }
        
        public GetBalanceRequestBody(string MakerCode, string ServiceCode, string DataSign) {
            this.MakerCode = MakerCode;
            this.ServiceCode = ServiceCode;
            this.DataSign = DataSign;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBalanceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBalanceResponse", Namespace="http://paygate.vtc.vn/VTCGateTopup", Order=0)]
        public TestBusiness.WSVTCGateTopup.GetBalanceResponseBody Body;
        
        public GetBalanceResponse() {
        }
        
        public GetBalanceResponse(TestBusiness.WSVTCGateTopup.GetBalanceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://paygate.vtc.vn/VTCGateTopup")]
    public partial class GetBalanceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetBalanceResult;
        
        public GetBalanceResponseBody() {
        }
        
        public GetBalanceResponseBody(string GetBalanceResult) {
            this.GetBalanceResult = GetBalanceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAccountInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAccountInfo", Namespace="http://paygate.vtc.vn/VTCGateTopup", Order=0)]
        public TestBusiness.WSVTCGateTopup.GetAccountInfoRequestBody Body;
        
        public GetAccountInfoRequest() {
        }
        
        public GetAccountInfoRequest(TestBusiness.WSVTCGateTopup.GetAccountInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://paygate.vtc.vn/VTCGateTopup")]
    public partial class GetAccountInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int AccountId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string MakerCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ServiceCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string DataSign;
        
        public GetAccountInfoRequestBody() {
        }
        
        public GetAccountInfoRequestBody(int AccountId, string MakerCode, string ServiceCode, string DataSign) {
            this.AccountId = AccountId;
            this.MakerCode = MakerCode;
            this.ServiceCode = ServiceCode;
            this.DataSign = DataSign;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAccountInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAccountInfoResponse", Namespace="http://paygate.vtc.vn/VTCGateTopup", Order=0)]
        public TestBusiness.WSVTCGateTopup.GetAccountInfoResponseBody Body;
        
        public GetAccountInfoResponse() {
        }
        
        public GetAccountInfoResponse(TestBusiness.WSVTCGateTopup.GetAccountInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://paygate.vtc.vn/VTCGateTopup")]
    public partial class GetAccountInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TestBusiness.WSVTCGateTopup.AccountInfo GetAccountInfoResult;
        
        public GetAccountInfoResponseBody() {
        }
        
        public GetAccountInfoResponseBody(TestBusiness.WSVTCGateTopup.AccountInfo GetAccountInfoResult) {
            this.GetAccountInfoResult = GetAccountInfoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface VTCGateTopupSoapChannel : TestBusiness.WSVTCGateTopup.VTCGateTopupSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class VTCGateTopupSoapClient : System.ServiceModel.ClientBase<TestBusiness.WSVTCGateTopup.VTCGateTopupSoap>, TestBusiness.WSVTCGateTopup.VTCGateTopupSoap {
        
        public VTCGateTopupSoapClient() {
        }
        
        public VTCGateTopupSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VTCGateTopupSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VTCGateTopupSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VTCGateTopupSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestBusiness.WSVTCGateTopup.CheckStatusTransactionResponse TestBusiness.WSVTCGateTopup.VTCGateTopupSoap.CheckStatusTransaction(TestBusiness.WSVTCGateTopup.CheckStatusTransactionRequest request) {
            return base.Channel.CheckStatusTransaction(request);
        }
        
        public TestBusiness.WSVTCGateTopup.VTCGateTransStateInfo CheckStatusTransaction(string MakerCode, string ServiceCode, long OrgTransId, string DataSign) {
            TestBusiness.WSVTCGateTopup.CheckStatusTransactionRequest inValue = new TestBusiness.WSVTCGateTopup.CheckStatusTransactionRequest();
            inValue.Body = new TestBusiness.WSVTCGateTopup.CheckStatusTransactionRequestBody();
            inValue.Body.MakerCode = MakerCode;
            inValue.Body.ServiceCode = ServiceCode;
            inValue.Body.OrgTransId = OrgTransId;
            inValue.Body.DataSign = DataSign;
            TestBusiness.WSVTCGateTopup.CheckStatusTransactionResponse retVal = ((TestBusiness.WSVTCGateTopup.VTCGateTopupSoap)(this)).CheckStatusTransaction(inValue);
            return retVal.Body.CheckStatusTransactionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestBusiness.WSVTCGateTopup.TopupAccountResponse TestBusiness.WSVTCGateTopup.VTCGateTopupSoap.TopupAccount(TestBusiness.WSVTCGateTopup.TopupAccountRequest request) {
            return base.Channel.TopupAccount(request);
        }
        
        public TestBusiness.WSVTCGateTopup.VTCGateResponse TopupAccount(string ServiceCode, string Account, double Amount, string MakerCode, System.DateTime TransDate, long OrgTransId, string DataSign) {
            TestBusiness.WSVTCGateTopup.TopupAccountRequest inValue = new TestBusiness.WSVTCGateTopup.TopupAccountRequest();
            inValue.Body = new TestBusiness.WSVTCGateTopup.TopupAccountRequestBody();
            inValue.Body.ServiceCode = ServiceCode;
            inValue.Body.Account = Account;
            inValue.Body.Amount = Amount;
            inValue.Body.MakerCode = MakerCode;
            inValue.Body.TransDate = TransDate;
            inValue.Body.OrgTransId = OrgTransId;
            inValue.Body.DataSign = DataSign;
            TestBusiness.WSVTCGateTopup.TopupAccountResponse retVal = ((TestBusiness.WSVTCGateTopup.VTCGateTopupSoap)(this)).TopupAccount(inValue);
            return retVal.Body.TopupAccountResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestBusiness.WSVTCGateTopup.CheckAccountEXISTSResponse TestBusiness.WSVTCGateTopup.VTCGateTopupSoap.CheckAccountEXISTS(TestBusiness.WSVTCGateTopup.CheckAccountEXISTSRequest request) {
            return base.Channel.CheckAccountEXISTS(request);
        }
        
        public string CheckAccountEXISTS(string ServiceCode, string Account, string MakerCode, string DataSign) {
            TestBusiness.WSVTCGateTopup.CheckAccountEXISTSRequest inValue = new TestBusiness.WSVTCGateTopup.CheckAccountEXISTSRequest();
            inValue.Body = new TestBusiness.WSVTCGateTopup.CheckAccountEXISTSRequestBody();
            inValue.Body.ServiceCode = ServiceCode;
            inValue.Body.Account = Account;
            inValue.Body.MakerCode = MakerCode;
            inValue.Body.DataSign = DataSign;
            TestBusiness.WSVTCGateTopup.CheckAccountEXISTSResponse retVal = ((TestBusiness.WSVTCGateTopup.VTCGateTopupSoap)(this)).CheckAccountEXISTS(inValue);
            return retVal.Body.CheckAccountEXISTSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestBusiness.WSVTCGateTopup.GetBalanceResponse TestBusiness.WSVTCGateTopup.VTCGateTopupSoap.GetBalance(TestBusiness.WSVTCGateTopup.GetBalanceRequest request) {
            return base.Channel.GetBalance(request);
        }
        
        public string GetBalance(string MakerCode, string ServiceCode, string DataSign) {
            TestBusiness.WSVTCGateTopup.GetBalanceRequest inValue = new TestBusiness.WSVTCGateTopup.GetBalanceRequest();
            inValue.Body = new TestBusiness.WSVTCGateTopup.GetBalanceRequestBody();
            inValue.Body.MakerCode = MakerCode;
            inValue.Body.ServiceCode = ServiceCode;
            inValue.Body.DataSign = DataSign;
            TestBusiness.WSVTCGateTopup.GetBalanceResponse retVal = ((TestBusiness.WSVTCGateTopup.VTCGateTopupSoap)(this)).GetBalance(inValue);
            return retVal.Body.GetBalanceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestBusiness.WSVTCGateTopup.GetAccountInfoResponse TestBusiness.WSVTCGateTopup.VTCGateTopupSoap.GetAccountInfo(TestBusiness.WSVTCGateTopup.GetAccountInfoRequest request) {
            return base.Channel.GetAccountInfo(request);
        }
        
        public TestBusiness.WSVTCGateTopup.AccountInfo GetAccountInfo(int AccountId, string MakerCode, string ServiceCode, string DataSign) {
            TestBusiness.WSVTCGateTopup.GetAccountInfoRequest inValue = new TestBusiness.WSVTCGateTopup.GetAccountInfoRequest();
            inValue.Body = new TestBusiness.WSVTCGateTopup.GetAccountInfoRequestBody();
            inValue.Body.AccountId = AccountId;
            inValue.Body.MakerCode = MakerCode;
            inValue.Body.ServiceCode = ServiceCode;
            inValue.Body.DataSign = DataSign;
            TestBusiness.WSVTCGateTopup.GetAccountInfoResponse retVal = ((TestBusiness.WSVTCGateTopup.VTCGateTopupSoap)(this)).GetAccountInfo(inValue);
            return retVal.Body.GetAccountInfoResult;
        }
    }
}
